<?php

/**
 * @file
 * owlcarousel_ui.module
 */

/**
 * Implements hook_theme().
 */
function owlcarousel_ui_theme() {
  return array(
    'owlcarousel_admin_settings_form' => array(
      'render element' => 'form',
    ),
    'owlcarousel_admin_settings_form_fields' => array(
      'render element' => 'form',
    ),
  );
}
 
/**
 * Implements hook_menu().
 */
function owlcarousel_ui_menu() {
  $items['admin/config/user-interface/owlcarousel'] = array(
    'title' => 'Owl Carousel',
    'description' => 'Owlcarousel instance settings list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('owlcarousel_settings_form'),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%'] = array(
    'title' => 'Owl Carousel Instance Settings',
    'description' => 'List instance settings.',
    'page callback' => 'owlcarousel_instance_settings_form',
    'page arguments' => array(4),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_CALLBACK,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('owlcarousel_global_settings_form'),
    'access arguments' => array('administer owlcarousel settings'),
    'weight' => 1,
    'type' => MENU_LOCAL_ACTION,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/import'] = array(
    'title' => 'Import Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('owlcarousel_variable_settings_import_form'),
    'access arguments' => array('administer owlcarousel settings'),
    'weight' => 2,
    'type' => MENU_LOCAL_ACTION,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%/export'] = array(
    'title' => 'Export Settings',
    'page callback' => 'owlcarousel_export_instance_settings',
    'page arguments' => array(4),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_CALLBACK,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%/delete/%'] = array(
    'title' => 'Delete Settings',
    'page callback' => 'owlcarousel_delete_instance_settings',
    'page arguments' => array(4, 6),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_CALLBACK,
    'file' => 'owlcarousel_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function owlcarousel_ui_permission() {
  return array(
    'administer owlcarousel settings' => array(
      'title' => t('Administer Owl Carousel settings'),
    ),
  );
}

/**
 * Helper function, return list of setting variables.
 */
function _owlcarousel_return_setting_vars() {
  $query = 'SELECT name FROM {variable} WHERE name LIKE :name';
  $results = db_query($query, array(':name' => db_like('owlcarousel_') . '%'))->fetchAll();

  return $results;
}
