<?php
/**
 * @file
 * galauto_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function galauto_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 3,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '01d2a359-3ece-4bf1-bf6e-7abc0bd39097',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 1,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '02b35e77-50fa-4c62-aebf-94a7fe9c5fdd',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 'Nissan',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '033a6ed2-bee1-4536-b786-b00b02275108',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'A-95',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '0345dc10-0d87-4bf3-b39e-3b1e76798447',
    'vocabulary_machine_name' => 'petrol_types',
  );
  $terms[] = array(
    'name' => 'Xin Kai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0703ed0b-2c6b-4fab-b0e6-c5627f5c69ed',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 5,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '0b4b94a6-0d5f-4f2a-bc4f-dfa5e99a72c5',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 'A-80',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '0bdd8109-104a-4f82-842d-74ed6c95bd6d',
    'vocabulary_machine_name' => 'petrol_types',
  );
  $terms[] = array(
    'name' => 'Brilliance',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0df36208-01de-4698-ac58-f1c9838fd58f',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Eagle',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0e997fd6-34c3-4557-8edb-e11fba7428cc',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Subaru',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0ed3f6fb-ae59-4eb6-87ea-7d8484ddc125',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'СМЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0f704068-9481-4912-81bd-70ff47549c60',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Cam and roller steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '0f9efab7-0bdc-4445-9d7d-94454ebe87c3',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'Oldsmobile',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '10f12f7f-02d0-4805-96a9-b96efccaef93',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Rear-drive',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '124e958b-d281-4c51-85d5-75d6e9f4c09d',
    'vocabulary_machine_name' => 'linkage',
  );
  $terms[] = array(
    'name' => 'Mitsubishi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '148cb7d8-d564-4220-9990-61ff69fa58ea',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Infiniti',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '14d44cad-4265-46b2-8386-d11569427b09',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Volvo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '14f1a22b-ed18-448a-851d-c1b76c90ffa7',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'ТагАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '17388ff0-4d33-4632-a8a5-183c26fd31cc',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Land Rover',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '184393c9-9213-4313-b604-4f4a8c0c95ac',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Gas',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '18d18102-8568-415a-bd43-2669bb0a7d83',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Great Wall',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1a29fa4a-8e16-4d70-b65d-c7f73a047809',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hafei',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1a3a5002-39d9-478a-9c94-691327ffae3a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Donkervoort',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1be0429b-93ab-45ab-9561-cb16ac06dd69',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'ShuangHuan',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1c304cac-b058-4d22-b3d7-95cfefec5ba3',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Aston Martin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1c9db532-7ba9-4588-a26b-824a09b8d87a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Rotary',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '1cef530c-87af-408a-a286-8038a323ad64',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'Front-drive',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '1dd458df-3714-4341-ade7-f4af1c729054',
    'vocabulary_machine_name' => 'linkage',
  );
  $terms[] = array(
    'name' => 'ЛУАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1fadfd46-da8d-4e13-b469-6c6093bcad2c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'УАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1fc55423-66a9-4764-aff0-92585c8d0f5f',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Station wagon',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 18,
    'uuid' => '20b3e4b8-82a3-4d64-8242-d8dc5be68530',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Wiesmann',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '20ba2c49-63fb-43b7-a612-1ab9abaa96e8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'ChangFeng',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '20e30c92-94a5-4750-9e9e-e3b08596c827',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Audi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2230d21c-ffb5-49cf-9374-fd623fdba91b',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Jeep',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '229ad3b9-4e82-4125-ba39-37165310da6d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Notchback',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '22beb334-be30-40d8-9009-f3d36c148d1d',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'TVR',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '24f5e8cd-02bf-4d70-96a1-a35597b09f8d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Wartburg',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '257e8b02-ff9f-4383-9c6a-475b3be4c9a1',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'A-98',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '263532c8-b581-4d9b-a302-fa82848118e6',
    'vocabulary_machine_name' => 'petrol_types',
  );
  $terms[] = array(
    'name' => 'Maserati',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '26b9120b-0c0b-45f6-a4bc-116c7a89568d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'ЗАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '27f47c9d-11db-419d-bbe0-25b3d106ba93',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Continuous injection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '29d5a025-1b9b-42d4-a449-b4611250c5e2',
    'vocabulary_machine_name' => 'fuel_injection',
  );
  $terms[] = array(
    'name' => 'Central port injection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2c3f09b2-3e8c-4de4-86ae-4139a34e32bd',
    'vocabulary_machine_name' => 'fuel_injection',
  );
  $terms[] = array(
    'name' => 'Cam and peg steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '2d5316a8-b641-43bd-a0e6-0923d4a3e7c6',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'BMW',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2db32408-bd5e-421f-a2cf-68cc11889889',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Euro VI',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '2eea6998-6ffb-4e19-a725-0a27fe9912e7',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'Austin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '350adf06-d3cb-453e-8d2d-9cac0570a5ee',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Swing axle',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '35d08eb9-9d22-4d9a-a3f9-0ee3bd2b1bc3',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Roadster',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '36fc6282-217d-4a09-b2c1-799412dbbc70',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'GMC',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '374e0bd7-f087-4510-b262-bdfda331ed72',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Vector',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3c1fe178-2fa5-45a0-b9f9-b7a04d3aab94',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Mitsuoka',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3f1dca86-0083-4d94-b5c1-674db8e2a03e',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Boxer',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3f2e8b0a-dc61-44c3-b016-6e2bcdb5a8fa',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'Hummer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3f6a1d3e-fe5a-4abc-bd90-a5220c57e80f',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Metrocab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3faa57ca-0130-44d2-8ad8-53110d63c44c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'DSG (Direct shift gearbox)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '435df231-3a09-4786-8eac-bb74ac569d68',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'Mini',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '43fafd19-ecf9-46cf-ac78-415b396e82bd',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'BYD',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '45487966-f301-4f84-a658-43db469edbb3',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Dong Feng',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4565bf36-d1c3-4254-b647-dcfbac097da4',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hydraulic brake',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '457c7fdf-dfde-471d-8c9b-b4c175e37118',
    'vocabulary_machine_name' => 'brake_system',
  );
  $terms[] = array(
    'name' => 'Euro I',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4839de80-553f-4773-bbe7-01247482cc3b',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'Aro',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '48f41c06-06ee-4719-859f-5e30f8e5e25a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Skoda',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4c224932-6cc4-4922-a1bf-c4dd7ff40560',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Worm and roller steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '4cface67-d9df-4c5b-94f4-abb40c9d108f',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'Dacia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4d03c1a0-80b1-4d47-be57-a8402f021aec',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Saturn',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5078b765-cd3d-44fc-b94a-f903f4ca4fe3',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'JAC',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '50b54643-28e6-4031-a679-47ca94303372',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Toyota',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '52aacf92-f820-4eb6-8308-381f702471ce',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Honda',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '52b21009-037b-4741-9684-22189d6e0b49',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Chrysler',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5393766c-3352-4a57-b21f-c0eff83d54f7',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Derways',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '53fec514-9bb6-421d-a635-113b625c7ef6',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Lexus',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '54de4bf6-8f35-44a0-9eec-0a8782661c22',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'A-92',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '5505e6df-f163-42ad-95dd-8d2a803ee767',
    'vocabulary_machine_name' => 'petrol_types',
  );
  $terms[] = array(
    'name' => 'Euro V',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '551d1b66-af33-40b6-ab9b-9b63dec1f3ff',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'ИЖ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '566f8956-9776-4514-b22e-fefa735de2ed',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'A-76',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '568f7d85-3601-4736-a451-50b4e4fdbd23',
    'vocabulary_machine_name' => 'petrol_types',
  );
  $terms[] = array(
    'name' => 'Geo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5715ea2f-1b57-40ba-909f-cf66affd3742',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Microcar',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '57b44017-0fbe-47a6-92d9-93b90608181c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Combi coupé',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '5816991b-e5b3-4d1b-8a8c-372efebcbcd1',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Hardtop',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '5a028928-e7c2-4dbb-aac7-60994574f2d7',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => '8x8',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '5c489c98-9f0e-4b22-b924-dfd7b32bc504',
    'vocabulary_machine_name' => 'linkage',
  );
  $terms[] = array(
    'name' => 'V-Type',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '5d0e84b2-da19-4141-8287-2192ebbda3a7',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'Chevrolet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5daa0326-a876-4657-a3a6-01f045ecd8db',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Москвич',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5df8f8fd-6be2-4591-b42c-3c696f661115',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Diesel',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5ee02179-59d5-4805-b973-130f8d316f23',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Renault',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '604a95e7-28b0-4a53-87c3-43a9948a3821',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hyundai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '613a9f9e-7a92-439b-b52b-0c58d517350a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => '4x4',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6439d064-963a-4e3d-871b-93b30f3007fb',
    'vocabulary_machine_name' => 'linkage',
  );
  $terms[] = array(
    'name' => 'Ethanol',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '65b03eb0-5102-4bae-aeb6-620efaca6a86',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Spyker',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '65ed11c4-44e0-4130-bcc1-e94292489cca',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Pontiac',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '67272571-f8f8-4ebd-b653-59508be73d0d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Euro II',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '69d9582e-6e11-45d2-b750-847efe89af4c',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'Ferrari',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6b1247da-1af3-4ddf-84db-ef49f7e1c94b',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Equal length A-arm (double wishbone)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6cdaf319-1d24-4319-849a-e5ccb5b76aba',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Euro IV',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '6e7e8225-14f1-4279-b33a-2bf836280bb1',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'Dadi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '70e2126c-0b8e-47a6-955d-5a3d638510e2',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Sport utility vehicle (SUV)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 16,
    'uuid' => '730682db-ea3e-4894-ba5d-618853662fc4',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Trailing link suspension',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '73cb2aba-f939-4dc7-a506-eeaafb6191e2',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Smart',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '740129de-4b8a-4a8c-9d3f-b0cce3dafcbd',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Crossover',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '76770486-6cf1-40cf-8138-757e045ecb94',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Daimler',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '778fd2d4-e747-4423-8070-57b3207abba8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Saleen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '79f9fa2c-6db7-4c05-9ea8-a555ff895371',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Rover',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7c223fd3-57ba-4305-8630-4b2debf00541',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Bugatti',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7ec4ebe3-bd39-4476-a292-43bbffbb1dbd',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Electric',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '7ffc53d5-1476-42a1-8438-0f9e8d158966',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Landwind',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8053292a-f8dd-49b5-8cf4-669fdb3d6e1e',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Daihatsu',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8094df53-a589-4e78-b67e-29f76647d4d4',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Saab',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '826c3569-3da5-4d2d-8443-282ebd813abf',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Coupé',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '82769a07-206d-4a40-839e-18f5cd70dee2',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Citroen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8347da35-f111-45f0-8126-c7bbf12d8a3d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Recirculating ball nut steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '83763774-ce0f-47ef-a245-937d88a4ac2d',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'Sedan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => '860e97a4-f3fe-4d88-a73b-d77b84538b9f',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Acura',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '86295160-e396-40af-84e0-692074dea884',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Alpina',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '87248a91-c6b0-41f8-b288-7900b98b0711',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'TipTronic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '88f1a7ab-c6dd-4dea-b837-9000997de532',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'Mahindra',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8c0afc38-df8d-46b5-8a03-dcb41bc03eab',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Cadillac',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8e0325ef-87b7-4cde-ac41-78549aff07e6',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Direct injection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '8e79ae24-baf8-466d-9e25-283d441ad0fa',
    'vocabulary_machine_name' => 'fuel_injection',
  );
  $terms[] = array(
    'name' => 2,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '8f33843d-4654-4010-8669-40cafa3635f6',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 'Hatchback',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '8f35c66f-891a-4f0b-8446-c101105a38e7',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Liftback',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '8f6eb9ee-5b54-4559-bfff-1faef7b55c0f',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Minivan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => '91118de9-6823-47c0-bbf8-7ce6eb95148c',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Ford',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '92114932-c882-4435-b17e-6d22c136004a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Automatic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '922d5600-32cf-4f95-9f1e-5c6afbf0a6d9',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'КАМАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '94f3229f-4719-4142-b2aa-7bd05157eae4',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'СеАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '95a56b7d-46ac-4422-8373-5c2718ceaf02',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Geely',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '95e1a23e-55fa-46c2-ab57-9218e84cddc9',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Tianye',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '96beaf96-995d-43a3-be16-f016c7af54e8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'MacPherson',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '977e5917-a318-498e-a7a9-d60f3fbea367',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Disc brake',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '98133797-f8bc-4074-b861-a3506ab8ebf0',
    'vocabulary_machine_name' => 'brake_system',
  );
  $terms[] = array(
    'name' => 'W-Type',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '981d13d2-faa0-4c6a-a042-090ea9ce6597',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'Suzuki',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '990158c6-1270-40de-8eac-a92cdaac8792',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 6,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '9a3e4ab1-49e6-4432-92ba-99fb62cdcc6e',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 'Isuzu',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9cadc9e7-d709-4ca1-8ac9-8f7a2a296a96',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Trabant',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9f163556-683f-4120-b164-35c0d34d6300',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Kia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a0188949-3133-44e5-9b74-d05e9c71f892',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Coggiola',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a22632c2-f716-4fe4-a33d-1f74c0a413e3',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Volkswagen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a343fc83-4143-4bcf-9003-85e98400fc55',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Town car',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 20,
    'uuid' => 'a47fb915-39cb-48c7-bc42-5b17d6897fdf',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Lincoln',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a7d08b6f-888a-49e1-9d2e-115bf3dfb7f5',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Buick',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a86c0085-52dc-4096-90c3-7b618f47f06e',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Велта',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a96b7055-2663-4a5b-8ce2-9c8e9668635a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Daewoo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aa16b8b4-fb14-4806-bc66-642ec50b6753',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Mazda',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aa26dd35-9136-4ddd-9a18-2ed50adba7c0',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Multiport fuel injection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'aab43955-c4f1-4756-8bbb-db386818a090',
    'vocabulary_machine_name' => 'fuel_injection',
  );
  $terms[] = array(
    'name' => 'Convertible (Cabriolet)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'ab6fe626-569d-4e85-99cd-e767879418a2',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'CVT (Continuous variable transmission)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'ad7136de-0a83-472b-8c1c-032150ab581f',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'ade79d8a-84e1-40fd-ab1a-8ab050d44eec',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'R8 Spyder',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aef37c07-473d-44d7-aafc-66d257c75ab5',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
    'parent' => array(
      0 => 'b4eb739a-235e-4122-9df8-b5dd2f103c51',
    ),
  );
  $terms[] = array(
    'name' => 'ЗИЛ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b064547f-1593-4e50-ad5e-28924882c466',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Chery',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b0aa61e2-e931-4581-ab0c-21e22e858c1d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Porsche',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b1e34751-b51c-4e4a-a5ec-0e841c765162',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Cam and double lever steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b441fd54-41af-45a4-8ab0-3f47e95ea6e1',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'Maybach',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b47a3a8a-853a-4400-bfac-aaa833f092c0',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'R',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b4eb739a-235e-4122-9df8-b5dd2f103c51',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
    'parent' => array(
      0 => '2230d21c-ffb5-49cf-9374-fd623fdba91b',
    ),
  );
  $terms[] = array(
    'name' => 'Touring car',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 19,
    'uuid' => 'b5cc4554-9920-4c13-b074-37f812161de9',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Morgan',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b85e5490-7c29-47fa-bd96-8a98396da788',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Asia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b87f38f3-1bd4-4805-8f10-1e3c855030a9',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Peugeot',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ba49539b-05f1-4f61-8f12-0ad11251c8bf',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hydrogen',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'bbf6fe07-9d18-45b9-87ea-f3871b88fcc9',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Semi automatic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'bf2efd19-0c76-454d-9fd5-4f8c1bd60e4e',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'Plymouth',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bfe9611d-bbce-42b2-b685-bf2d48053e8a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'SsangYong',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c053904a-07c7-46ad-b33c-05ee2b5690d2',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Iran Khodro',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0629cfa-53f7-4b2f-a157-96b384caf8c8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Caterham',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c0dbe843-8930-4cdb-8151-440412c0a82a',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Euro III',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'c27f6256-e1d5-4059-8256-49d506e77e04',
    'vocabulary_machine_name' => 'ecological_standard',
  );
  $terms[] = array(
    'name' => 'Opel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c2ebe0d0-10b3-4f89-95c9-25690e11e950',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'MG',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c45caa42-4cc9-47d7-be90-d835a8475d3c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'ВАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c487d6e1-408b-40a0-be23-90f60443cf79',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'SEAT',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c53f7881-1f0d-48ea-aced-3223814e22b0',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Petrol',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'c69c7f23-13b8-452b-a97d-cf166ee8a05f',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Lamborghini',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c83fe9a9-c742-4d03-95ac-d1c2a11ca8f5',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Doninvest',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c8dc8a9b-5f61-45e6-ad04-b47521961f5e',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Pneumatic brake',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'c91beb55-0528-4038-a279-bb6423c0612b',
    'vocabulary_machine_name' => 'brake_system',
  );
  $terms[] = array(
    'name' => 'Solid beam axle',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'c9fe24e6-7b6e-49a2-a371-15fc8919f712',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Tianma',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cbabce08-bf90-477b-93fe-ba0244dfcac9',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Proton',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cc817b10-95a5-4acf-afcd-a2e05d925148',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Rack and pinion steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'cdc403e7-dc30-4920-8674-e0f62e0a11e9',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'Limousine',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => 'cdd9f0cc-cfb3-4f3c-adfa-5b73ad054c02',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Lotus',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ceb62ef0-c38b-48f6-b606-4eeb6e6e7944',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Drum brake',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'd1c58b4b-6245-43fd-972b-8639c93bfc28',
    'vocabulary_machine_name' => 'brake_system',
  );
  $terms[] = array(
    'name' => 'Mercedes-Benz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd426a1c8-27a2-4638-b159-2683d341281f',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Maruti',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd5951058-2fbb-4c75-8e84-5b5c44ea71c8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Diesel',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'd6a090d1-5689-43e5-a7d9-bde33d211f21',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'Manual',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'd8ea66df-7e3a-412d-8f0d-0a32188e5511',
    'vocabulary_machine_name' => 'gearbox_types',
  );
  $terms[] = array(
    'name' => 'Mercury',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd90dcd7e-6c27-45b9-8afe-49bdea131718',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Koenigsegg',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dc53e846-f45e-4e38-a4e9-584596e8474c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Unequal length double A-arm',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'ddfeeeba-6124-41bf-a995-cda583d0af02',
    'vocabulary_machine_name' => 'front_suspension',
  );
  $terms[] = array(
    'name' => 'Coupe Utility',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'de0e4306-bebb-4dd6-97a2-86876df1c0c8',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Jaguar',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'de13f54f-6413-4373-9426-06e1d26e0910',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => '2+2',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'de769bbc-4845-4b51-8e8f-29251002653a',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Pagani',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dfc27103-67d6-4397-8bf4-7c15537d3271',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Tatra',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dfc7bd7c-c8bf-4f64-a90b-265d57c12941',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Stanhope body',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 17,
    'uuid' => 'e030ca00-c16d-4976-baae-b9219f2f7930',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Single-point injection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'e278a87c-2545-45c4-969d-cd3bdd54b155',
    'vocabulary_machine_name' => 'fuel_injection',
  );
  $terms[] = array(
    'name' => 'Worm and sector steering gear.',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'e2c800e9-ca1b-4e4b-ba54-aac67e603dda',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 4,
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'e5cb9d78-15ac-4af7-9dcb-b6f85c47c63a',
    'vocabulary_machine_name' => 'number_of_valves_per_cylinder',
  );
  $terms[] = array(
    'name' => 'ZX',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e5eef6e6-6edb-445a-87c7-722b03d38fe8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'PUCH',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e6dd9dd0-1fad-4e4c-ba39-b536d9cac1f2',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Lancia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'eb665371-0847-44df-b750-693dd733e822',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Lifan',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ece852b8-5415-4aee-abed-465e8b58b690',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Rolls-Royce',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed7259fe-5204-4549-9ee6-9db642dec58d',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Bentley',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ee2d6081-086d-49ba-b133-c8e0a80b5529',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Inline',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'eeadf6a3-c63f-41e1-a1d2-e06691e65f08',
    'vocabulary_machine_name' => 'disposition_of_cylinders',
  );
  $terms[] = array(
    'name' => 'ГАЗ',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f614fb9e-14ae-4350-a3ea-5cd71720adc1',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Sedan delivery',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 15,
    'uuid' => 'f8506887-18b5-4ff6-9db4-393dc8e405a2',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'Dodge',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f888461b-75a0-4c88-ba44-db97835a2dda',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hearse',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'f8ca9935-2af9-4567-820c-5b2e9ec39d73',
    'vocabulary_machine_name' => 'cars_body_type',
  );
  $terms[] = array(
    'name' => 'FAW',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f9855e2f-d4ef-4928-b27b-d6b91e04551b',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Alfa Romeo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f9b9e8f4-97c3-4939-a1e4-1c043e799dce',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Worm and ball bearing nut steering gear',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'fa66616f-f136-4de7-9c1a-8918e7111973',
    'vocabulary_machine_name' => 'steering_gear',
  );
  $terms[] = array(
    'name' => 'HuangHai',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fbd11c10-682b-4543-b09a-7e0a632599b8',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Hybrid',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'fd96c735-59da-4784-b58a-eb66a8ce5fec',
    'vocabulary_machine_name' => 'engine_type',
  );
  $terms[] = array(
    'name' => 'Scion',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff6d4707-0157-4809-922c-b914feb96dd5',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  $terms[] = array(
    'name' => 'Fiat',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff8ec1e2-aeca-44bb-b8bd-986b749acf1c',
    'vocabulary_machine_name' => 'auto_created_voc2_956',
  );
  return $terms;
}
