<?php

/**
 * @file
 * Install, update and uninstall functions for the advert module.
 */

/**
 * Implements hook_install().
 */
function advert_install() {
  // Ensure the advert node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['advert']);
}

/**
 * Implements hook_uninstall().
 */
function advert_uninstall() {
  variable_del('advert_block_count');
}
