<?php

/**
 * @file
 * Install, update and uninstall functions for the gallery module.
 */

/**
 * Implements hook_install().
 */
function gallery_install() {
  // Ensure the blog node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['gallery']);
}

/**
 * Implements hook_uninstall().
 */
function gallery_uninstall() {
  variable_del('gallery_block_count');
}
