<?php

/**
 * @file
 * Install, update and uninstall functions for the organization module.
 */

/**
 * Implements hook_install().
 */
function organization_install() {
  // Ensure the organization node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['organization']);
}

/**
 * Implements hook_uninstall().
 */
function organization_uninstall() {
  variable_del('organization_block_count');
}
