<?php

/**
 * @file
 * Install, update and uninstall functions for the news module.
 */

/**
 * Implements hook_install().
 */
function news_install() {
  // Ensure the news node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['news']);
}

/**
 * Implements hook_uninstall().
 */
function news_uninstall() {
  variable_del('news_block_count');
}
